hamrocart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from .views import test, index, register, product, check_uniqueness, category, search

urlpatterns = [
    path('', index),
    path('test', test),
    path('register', register, name='register'),
    path('products/<product_slug>', product, name='product_page'),
    path('search', search, name='search'),
    path('categories/<category_slug>', category, name='category_page'),
    path('check-username/<username>', check_uniqueness, name='check_uniqueness')
]

shop/models.py
from django.db import models
from autoslug import AutoSlugField
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from sorl.thumbnail import ImageField


# Create your models here.

class Category(models.Model):
    title = models.CharField(max_length=200)
    slug = AutoSlugField(populate_from='title')

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.title


class Product(models.Model):
    title = models.CharField(max_length=200)
    slug = AutoSlugField(populate_from='title')
    price = models.FloatField(null=True)
    details = RichTextField()
    featured = models.BooleanField()
    brand_name = models.CharField(max_length=200)
    image = ImageField(upload_to='products')
    view_count = models.BigIntegerField(default=0)
    pub_date = models.DateTimeField(auto_now=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Review(models.Model):
    rating = models.IntegerField()
    comment = models.TextField()
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class Slider(models.Model):
    image = ImageField(upload_to='slides')
    caption = models.CharField(max_length=255)

    def __str__(self):
        return self.caption

shop/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm
from .models import Review


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['rating', 'comment']

shop/views.py
from django.shortcuts import render, redirect
from .forms import SignUpForm, ReviewForm
from .models import Slider, Product, Category
from django.contrib.auth.models import User
from django.http import JsonResponse


# Create your views here.

def index(request):
    slides = Slider.objects.all()
    featured_products = Product.objects.filter(featured=True).all()
    latest_products = Product.objects.order_by('-pub_date')[:8]
    categories = Category.objects.order_by('title').all()
    context = {
        'slides': slides,
        'featured_products': featured_products,
        'latest_products': latest_products,
        'categories': categories
    }
    return render(request, 'shop/index.html', context)


def test(request):
    return render(request, 'shop/test.html')


def register(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/accounts/login')
    else:
        form = SignUpForm()
    context = {'form': form}
    return render(request, 'registration/register.html', context)


def product(request, product_slug):
    pro = Product.objects.get(slug=product_slug)
    form = ReviewForm()
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.product = pro
            review.user = request.user
            review.save()

    categories = Category.objects.order_by('title').all()
    context = {
        'product': pro,
        'categories': categories,
        'form': form
    }

    return render(request, 'shop/product.html', context)


def check_uniqueness(request, username):
    exists = User.objects.filter(username=username).exists()
    return JsonResponse({'exists': exists})


def category(request, category_slug):
    cat = Category.objects.get(slug=category_slug)
    categories = Category.objects.order_by('title').all()

    return render(request, 'shop/category.html', {'category': cat, 'categories': categories})


def search(request):
    categories = Category.objects.order_by('title').all()
    q = request.GET.get('search', None)

    if q:
        products = Product.objects.filter(title__contains=q)
        return render(request, 'shop/search.html', {
            'categories': categories,
            'search': q,
            'products': products
        })
    else:
        return redirect('/')

shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <title>Hamrocart</title>

    <!-- Google font -->
    <link href="https://fonts.googleapis.com/css?family=Hind:400,700" rel="stylesheet">

    <!-- Bootstrap -->
    <link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>

    <!-- Slick -->
    <link type="text/css" rel="stylesheet" href="{% static 'css/slick.css' %}"/>
    <link type="text/css" rel="stylesheet" href="{% static 'css/slick-theme.css' %}"/>

    <!-- nouislider -->
    <link type="text/css" rel="stylesheet" href="{% static 'css/nouislider.min.css' %}"/>

    <!-- Font Awesome Icon -->
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">

    <!-- Custom stlylesheet -->
    <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}"/>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->

</head>

<body>
<!-- HEADER -->
<header>
    <!-- top Header -->
    <div id="top-header">
        <div class="container">
            <div class="pull-left">
                <span>Welcome to Hamrocart!</span>
            </div>
        </div>
    </div>
    <!-- /top Header -->

    <!-- header -->
    <div id="header">
        <div class="container">
            <div class="pull-left">
                <!-- Logo -->
                <div class="header-logo">
                    <a class="logo" href="/">
                        <img src="{% static 'img/logo.png' %}" alt="">
                    </a>
                </div>
                <!-- /Logo -->

                <!-- Search -->
                <div class="header-search">
                    <form action="{% url 'search' %}">
                        <input class="input search-input" type="text" placeholder="Enter your keyword" name="search">
                        <select class="input search-categories" name="category_id">
                            <option value="0">All Categories</option>
                            {% for category in categories %}
                                <option value="{{ category.id }}">{{ category.title }}</option>
                            {% endfor %}
                        </select>
                        <button class="search-btn" type="submit"><i class="fa fa-search"></i></button>
                    </form>
                </div>
                <!-- /Search -->
            </div>
            <div class="pull-right">
                <ul class="header-btns">
                    <!-- Account -->
                    <li class="header-account dropdown default-dropdown">
                        <div class="dropdown-toggle" role="button" data-toggle="dropdown" aria-expanded="true">
                            <div class="header-btns-icon">
                                <i class="fa fa-user-o"></i>
                            </div>
                            <strong class="text-uppercase">

                                {% if user.is_authenticated %}
                                    {{ user.username }}
                                {% else %}
                                    My Account
                                {% endif %}

                            </strong>
                        </div>

                        {% if user.is_authenticated %}
                             <a href="{% url 'logout' %}" class="text-uppercase">Logout</a>
                        {% else %}
                            <a href="{% url 'login' %}" class="text-uppercase">Login</a>/
                            <a href="{% url 'register' %}" class="text-uppercase">Join</a>
                        {% endif %}
                    </li>
                    <!-- /Account -->

                    <!-- Cart -->
                    <li class="header-cart dropdown default-dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                            <div class="header-btns-icon">
                                <i class="fa fa-shopping-cart"></i>
                                <span class="qty">3</span>
                            </div>
                            <strong class="text-uppercase">My Cart:</strong>
                            <br>
                            <span>35.20$</span>
                        </a>
                    </li>
                    <!-- /Cart -->

                    <!-- Mobile nav toggle-->
                    <li class="nav-toggle">
                        <button class="nav-toggle-btn main-btn icon-btn"><i class="fa fa-bars"></i></button>
                    </li>
                    <!-- / Mobile nav toggle -->
                </ul>
            </div>
        </div>
        <!-- header -->
    </div>
    <!-- container -->
</header>
<!-- /HEADER -->

<!-- NAVIGATION -->
<div id="navigation">
    <!-- container -->
    <div class="container">
        <div id="responsive-nav">
            <!-- category nav -->
            <div class="category-nav show-on-click">
                <span class="category-header">Categories <i class="fa fa-list"></i></span>
                <ul class="category-list {% if request.path == '/' %} open {% endif %}">

                    {% for category in categories %}
                        <li><a href="{% url 'category_page' category.slug %}">{{ category.title }}</a></li>
                    {% endfor %}

                </ul>
            </div>
            <!-- /category nav -->

            <!-- menu nav -->
            <div class="menu-nav">
                <span class="menu-header">Menu <i class="fa fa-bars"></i></span>
                <ul class="menu-list">
                    {% for category in categories %}
                        <li><a href="{% url 'category_page' category.slug %}">{{ category.title }}</a></li>
                    {% endfor %}

                </ul>
            </div>
            <!-- menu nav -->
        </div>
    </div>
    <!-- /container -->
</div>
<!-- /NAVIGATION -->


<!-- section -->
<div class="section">
    <!-- container -->
    <div class="container">
        {% block content %} {% endblock %}
    </div>
    <!-- /container -->
</div>
<!-- /section -->

<!-- FOOTER -->
<footer id="footer" class="section section-grey">
    <!-- container -->
    <div class="container">
        <!-- row -->
        <div class="row">
            <!-- footer widget -->
            <div class="col-md-3 col-sm-6 col-xs-6">
                <div class="footer">
                    <!-- footer logo -->
                    <div class="footer-logo">
                        <a class="logo" href="#">
                            <img src="./img/logo.png" alt="">
                        </a>
                    </div>
                    <!-- /footer logo -->

                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut
                        labore et dolore magna</p>

                    <!-- footer social -->
                    <ul class="footer-social">
                        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                        <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                        <li><a href="#"><i class="fa fa-pinterest"></i></a></li>
                    </ul>
                    <!-- /footer social -->
                </div>
            </div>
            <!-- /footer widget -->


            <!-- /footer widget -->

            <div class="clearfix visible-sm visible-xs"></div>

            <!-- footer widget -->

            <!-- /footer widget -->

            <!-- footer subscribe -->
            <!-- /footer subscribe -->
        </div>
        <!-- /row -->
        <hr>
        <!-- row -->
        <div class="row">
            <div class="col-md-8 col-md-offset-2 text-center">
                <!-- footer copyright -->
                <div class="footer-copyright">
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;<script>document.write(new Date().getFullYear());</script>
                    All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by
                    <a href="https://colorlib.com" target="_blank">Colorlib</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </div>
                <!-- /footer copyright -->
            </div>
        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
</footer>
<!-- /FOOTER -->

<!-- jQuery Plugins -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/slick.min.js' %}"></script>
<script src="{% static 'js/nouislider.min.js' %}"></script>
<script src="{% static 'js/jquery.zoom.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>


{% block scripts %} {% endblock %}

</body>

</html>

shop/templates/shop/category.html
{% extends 'shop/base.html' %}
{% load thumbnail %}

{% block content %}
    <!-- section -->
    <div class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">
                <!-- section title -->
                <div class="col-md-12">
                    <div class="section-title">
                        <h2 class="title">{{ category.title }}</h2>
                    </div>
                </div>
                <!-- section title -->
                {% for product in category.product_set.all %}

                    <!-- Product Single -->
                    <div class="col-md-3 col-sm-6 col-xs-6">
                        <div class="product product-single">
                            <div class="product-thumb">

                                {% thumbnail product.image "270x360" crop="center" as im %}
                                    <img src="{{ im.url }}" alt="">
                                {% endthumbnail %}

                            </div>
                            <div class="product-body">
                                <h3 class="product-price">NRS {{ product.price }}</h3>
                                <div class="product-rating">
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star-o empty"></i>
                                </div>
                                <h2 class="product-name"><a href="{% url 'product_page' product.slug %}">{{ product.title }}</a></h2>
                                <div class="product-btns">
                                    <button class="primary-btn add-to-cart"><i class="fa fa-shopping-cart"></i> Add to
                                        Cart
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /Product Single -->

                {% endfor %}

            </div>

        </div>
        <!-- /container -->
    </div>
    <!-- /section -->
{% endblock %}

shop/templates/shop/index.html
{% extends 'shop/base.html' %}

{% load thumbnail %}

{% block content %}
    <!-- HOME -->
    <div id="home">
        <!-- container -->
        <div class="container">
            <!-- home wrap -->
            <div class="home-wrap">
                <!-- home slick -->
                <div id="home-slick">

                    {% for slide in slides %}
                        <!-- banner -->
                        <div class="banner banner-1">
                            {% thumbnail slide.image "1200x675" crop="center" as im %}
                                <img src="{{ im.url }}" alt="">
                            {% endthumbnail %}
                            <div class="banner-caption text-center">
                                <h3 class="white-color font-weak">{{ slide.caption }}</h3>
                            </div>
                        </div>
                        <!-- /banner -->
                    {% endfor %}

                </div>
                <!-- /home slick -->
            </div>
            <!-- /home wrap -->
        </div>
        <!-- /container -->
    </div>
    <!-- /HOME -->

    <!-- section -->
    <div class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">
                <!-- section title -->
                <div class="col-md-12">
                    <div class="section-title">
                        <h2 class="title">Latest Products</h2>
                    </div>
                </div>
                <!-- section title -->
                {% for product in latest_products %}

                    <!-- Product Single -->
                    <div class="col-md-3 col-sm-6 col-xs-6">
                        <div class="product product-single">
                            <div class="product-thumb">

                                {% thumbnail product.image "270x360" crop="center" as im %}
                                    <img src="{{ im.url }}" alt="">
                                {% endthumbnail %}

                            </div>
                            <div class="product-body">
                                <h3 class="product-price">NRS {{ product.price }}</h3>
                                <div class="product-rating">
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star-o empty"></i>
                                </div>
                                <h2 class="product-name"><a href="{% url 'product_page' product.slug %}">{{ product.title }}</a></h2>
                                <div class="product-btns">
                                    <button class="primary-btn add-to-cart"><i class="fa fa-shopping-cart"></i> Add to
                                        Cart
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /Product Single -->

                {% endfor %}

            </div>
            <!-- /row -->
            <!-- row -->
            <div class="row">
                <!-- section title -->
                <div class="col-md-12">
                    <div class="section-title">
                        <h2 class="title">Featured Products</h2>
                    </div>
                </div>
                <!-- section title -->

                {% for product in featured_products %}

                    <!-- Product Single -->
                    <div class="col-md-3 col-sm-6 col-xs-6">
                        <div class="product product-single">
                            <div class="product-thumb">

                                {% thumbnail product.image "270x360" crop="center" as im %}
                                    <img src="{{ im.url }}" alt="">
                                {% endthumbnail %}

                            </div>
                            <div class="product-body">
                                <h3 class="product-price">NRS {{ product.price }}</h3>
                                <div class="product-rating">
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star-o empty"></i>
                                </div>
                                <h2 class="product-name"><a href="{% url 'product_page' product.slug %}">{{ product.title }}</a></h2>
                                <div class="product-btns">
                                    <button class="primary-btn add-to-cart"><i class="fa fa-shopping-cart"></i> Add to
                                        Cart
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /Product Single -->

                {% endfor %}

            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /section -->

{% endblock %}

shop/templates/shop/product.html
{% extends 'shop/base.html' %}

{% load thumbnail %}

{% load app_filters %}

{% block content %}
    <div class="row">
        <!--  Product Details -->
        <div class="product product-details clearfix">
            <div class="col-md-6">
                <div id="product-main-view">
                    <div class="product-view">
                        {% thumbnail product.image "1200x1200" crop="center" as im %}
                            <img src="{{ im.url }}" alt="">
                        {% endthumbnail %}
                    </div>

                </div>
                <div id="product-view">
                    <div class="product-view">
                        {% thumbnail product.image "300x300" crop="center" as im %}
                            <img src="{{ im.url }}" alt="">
                        {% endthumbnail %}
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="product-body">
                    <div class="product-label">
                        <span>{{ product.category.title }}</span>
                    </div>

                    <h2 class="product-name">{{ product.title }}</h2>
                    <h3 class="product-price">NRs {{ product.price }}</h3>
                    <div>
                        <a href="#">{{ product.review_set.count }} Review(s)</a>
                    </div>
                    <p><strong>Brand:</strong> {{ product.brand_name }}</p>


                    <div class="product-btns">
                        <button class="primary-btn add-to-cart"><i class="fa fa-shopping-cart"></i> Add to Cart</button>
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <div class="product-tab">
                    <ul class="tab-nav">
                        <li class="active"><a data-toggle="tab" href="#tab1">Description</a></li>
                        <li><a data-toggle="tab" href="#tab2">Reviews ({{ product.review_set.count }})</a></li>
                    </ul>
                    <div class="tab-content">
                        <div id="tab1" class="tab-pane fade in active">
                            {{ product.details | safe }}
                        </div>
                        <div id="tab2" class="tab-pane fade in">

                            <div class="row">
                                <div class="col-md-6">
                                    <div class="product-reviews">

                                        {% for review in product.review_set.all %}
                                            <div class="single-review">
                                                <div class="review-heading">
                                                    <div><a href="#"><i
                                                            class="fa fa-user-o"></i> {{ review.user.username }}</a>
                                                    </div>
                                                    <div><a href="#"><i class="fa fa-clock-o"></i> {{ review.pub_date }}
                                                    </a>
                                                    </div>
                                                    <div class="review-rating pull-right">
                                                        {% for star in review.rating|range %}
                                                            <i class="fa fa-star"></i>
                                                        {% endfor %}
                                                    </div>
                                                </div>
                                                <div class="review-body">
                                                    <p>{{ review.comment }}</p>
                                                </div>
                                            </div>
                                        {% endfor %}


                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <h4 class="text-uppercase">Write Your Review</h4>
                                    <p>Your email address will not be published.</p>
                                    <form class="review-form" method="post">
                                        {% csrf_token %}
                                        <div class="form-group">
                                            <textarea class="input" name="comment" placeholder="Your review"></textarea>
                                        </div>
                                        <div class="form-group">
                                            <div class="input-rating">
                                                <strong class="text-uppercase">Your Rating: </strong>
                                                <div class="stars">
                                                    <input type="radio" id="star5" name="rating" value="5"/><label
                                                        for="star5"></label>
                                                    <input type="radio" id="star4" name="rating" value="4"/><label
                                                        for="star4"></label>
                                                    <input type="radio" id="star3" name="rating" value="3"/><label
                                                        for="star3"></label>
                                                    <input type="radio" id="star2" name="rating" value="2"/><label
                                                        for="star2"></label>
                                                    <input type="radio" id="star1" name="rating" value="1"/><label
                                                        for="star1"></label>
                                                </div>
                                            </div>
                                        </div>
                                        {% if user.is_authenticated %}
                                            <button class="primary-btn">Submit</button>
                                        {% endif %}
                                    </form>
                                </div>
                            </div>


                        </div>
                    </div>
                </div>
            </div>

        </div>
        <!-- /Product Details -->
    </div>
{% endblock %}

shop/templates/shop/test.html
{% extends 'shop/base.html' %}

{% block content %}
    testing
{% endblock %}